name: Tests

on:
  push:

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.2']
        laravel: ['10.*']
        stability: ['prefer-lowest', 'prefer-stable']

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }} - ${{ matrix.stability }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ matrix.php }}

      - name: Install dependencies
        run: |
          composer require "illuminate/contracts:${{ matrix.laravel }}" --no-interaction --no-update --ansi
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction --ansi

      - name: Test php code
        run: composer test:unit
